
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AvgPainterMobile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AvgPainterMobile
  pod 'ChromaColorPicker'

  target 'AvgPainterMobileTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'AvgPainterMobileUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
